---
- name: make sure exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /usr/local/share/tessdata

- name: prepare base lib
  unarchive:
    src: "{{ yjyx_files_path }}/opencv_ocr/{{ item.src }}"
    dest: /tmp/
  with_items:
    - src: pkgconfig-0.17.2.tar.bz2
    - src: opencv-3.2.0.zip
    - src: tesseract.tar.gz
    - src: leptonica-1.74.tar.gz

- name: prepare apache maven
  unarchive:
    src: "{{ yjyx_files_path }}/opencv_ocr/apache-maven-3.5.2-bin.tar.gz"
    dest: /usr/local/

- name: install pkgconfig
  shell: "{{ item }}"
  args:
    chdir: /tmp/pkgconfig-0.17.2/
  with_items:
    - ./configure
    - make -j8
    - make install

- name: install opencv lib
  shell: "{{ item }}"
  args:
    chdir: /tmp/opencv-3.2.0/
  with_items:
    - cmake -D WITH_IPP=OFF -D WITH_OPENCL=OFF WITH_GTK_2_X=ON -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local /tmp/opencv-3.2.0/
    - make -j8
    - make install

- name: install leptonica
  shell: "{{ item }}"
  args:
    chdir: /tmp/leptonica-1.74/
  with_items:
    - ./autobuild
    - ./configure
    - make
    - make install

- name: install tesseract
  shell: "{{ item }}"
  args:
    chdir: /tmp/tesseract/
  with_items:
    - ./autogen.sh
    - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig LIBLEPT_HEADERSDIR=/usr/local/include ./configure --with-extra-includes=/usr/local/include --with-extra-libraries=/usr/local/lib
    - LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" make
    - make install
    - ldconfig

- name: copy data file
  copy:
    src: "{{ yjyx_files_path }}/opencv_ocr/{{ item.src }}"
    dest: /usr/local/share/tessdata/
  with_items:
    - src: wni_l.traineddata
    - src: eng.traineddata
    - src: chi_sim.traineddata

- name: config apache maven
  command: sed -i '{{ item }}' /etc/profile
  with_items:
    - s/.*MAVEN_HOME.*//g
    - $a MAVEN_HOME=/usr/local/apache-maven-3.5.2\nexport MAVEN_HOME\nexport PATH=${PATH}:${MAVEN_HOME}/bin

- shell: source /etc/profile
